set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86)

set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)

set(CMAKE_C_COMPILER_TARGET i686-w64-mingw32)
set(CMAKE_CXX_COMPILER_TARGET i686-w64-mingw32)

set(CMAKE_SHARED_LINKER_FLAGS "-fuse-ld=lld -pthread")
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)