/* Sonic Adventure 2: Battle Model
 * 
 * Generated by SALVL
 * 
 * Description: objLandTableChaoStgHero
 * 
 */

enum al_stg_hero_texTexName
{
	al_stg_hero_texTexName_cascade_a00,
	al_stg_hero_texTexName_g_heroemblem,
	al_stg_hero_texTexName_g_heroemblem2,
	al_stg_hero_texTexName_g_herofunsui03,
	al_stg_hero_texTexName_g_herofunsui05,
	al_stg_hero_texTexName_g_herofunsui06,
	al_stg_hero_texTexName_g_herofunsui07,
	al_stg_hero_texTexName_g_herofunsui08,
	al_stg_hero_texTexName_g_herofunsui09,
	al_stg_hero_texTexName_g_herofunsui10,
	al_stg_hero_texTexName_g_herohasi01,
	al_stg_hero_texTexName_g_herohasi02,
	al_stg_hero_texTexName_g_herohasira01,
	al_stg_hero_texTexName_g_herohasira02,
	al_stg_hero_texTexName_g_herohasira03,
	al_stg_hero_texTexName_g_herohasira04,
	al_stg_hero_texTexName_g_herohasira05,
	al_stg_hero_texTexName_g_herohasira06,
	al_stg_hero_texTexName_g_heroiwa02,
	al_stg_hero_texTexName_g_heroiwa03,
	al_stg_hero_texTexName_g_herokabe02,
	al_stg_hero_texTexName_g_herokabe03,
	al_stg_hero_texTexName_g_herokawa01,
	al_stg_hero_texTexName_g_herokawa02,
	al_stg_hero_texTexName_g_herokawa03,
	al_stg_hero_texTexName_g_herosiba01,
	al_stg_hero_texTexName_g_herosiba02,
	al_stg_hero_texTexName_g_herosky03,
	al_stg_hero_texTexName_g_herosky04,
	al_stg_hero_texTexName_g_heroskyb,
	al_stg_hero_texTexName_g_heroskyf01,
	al_stg_hero_texTexName_g_heroskyf02,
	al_stg_hero_texTexName_g_heroyane01,
	al_stg_hero_texTexName_hwater_a00,
	al_stg_hero_texTexName_kin_kogold,
	al_stg_hero_texTexName_water_b00,
	al_stg_hero_texTexName_g_herokabe05
};

SA2B_PositionData position_000101DC[] = {
	{ 987.2689f, -455, 570 },
	{ 1140, 268, 0 },
	{ 987.2689f, 268, -570 },
	{ 570, 268, -987.2689f },
	{ -0.00001f, 268, -1140 },
	{ -570, 268, -987.2689f },
	{ -987.2689f, 268, -570 },
	{ -1140, 268, 0.000001f },
	{ -987.2689f, 268, 570 },
	{ -570, 268, 987.2689f },
	{ 0.000001f, 268, 1140 },
	{ 570, 268, 987.2689f },
	{ 987.2689f, 268, 570 },
	{ -1140, -455, 0.000001f },
	{ -987.2689f, -455, -570 },
	{ -570, -455, -987.2689f },
	{ -0.00001f, -455, -1140 },
	{ -987.2689f, -455, 570 },
	{ 570, -455, -987.2689f },
	{ -570, -455, 987.2689f },
	{ 987.2689f, -455, -570 },
	{ 0.000001f, -455, 1140 },
	{ 1140, -455, 0 },
	{ 570, -455, 987.2689f }
};

SA2B_Color0Data vcolor_000102FC[] = {
	{ 0xF4E6F8FF },
	{ 0xFFFFFFFF },
	{ 0xFFFFFFFF },
	{ 0xFFFFFFFF },
	{ 0xFFFFFFFF },
	{ 0xFFFFFFFF },
	{ 0xFFFFFFFF },
	{ 0xFFFFFFFF },
	{ 0xFFFFFFFF },
	{ 0xFFFFFFFF },
	{ 0xFFFFFFFF },
	{ 0xFFFFFFFF },
	{ 0xFFFFFFFF },
	{ 0xF4E6F8FF },
	{ 0xF4E6F8FF },
	{ 0xF4E6F8FF },
	{ 0xF4E6F8FF },
	{ 0xF4E6F8FF },
	{ 0xF4E6F8FF },
	{ 0xF4E6F8FF },
	{ 0xF4E6F8FF },
	{ 0xF4E6F8FF },
	{ 0xF4E6F8FF },
	{ 0xF4E6F8FF }
};

SA2B_Tex0Data uv_0001035C[] = {
	{ 768, 0 },
	{ 1024, 0 },
	{ 768, 255 },
	{ 1024, 255 },
	{ 1280, 0 },
	{ 1536, 0 },
	{ 1280, 255 },
	{ 1536, 255 },
	{ 1792, 0 },
	{ 2048, 0 },
	{ 1792, 255 },
	{ 2048, 255 },
	{ 256, 0 },
	{ 512, 0 },
	{ 256, 255 },
	{ 512, 255 },
	{ 2304, 0 },
	{ 2560, 0 },
	{ 2304, 255 },
	{ 2560, 255 },
	{ 2816, 0 },
	{ 3072, 0 },
	{ 2816, 255 },
	{ 3072, 255 },
	{ 512, 0 },
	{ 768, 0 },
	{ 512, 255 },
	{ 768, 255 },
	{ 1536, 0 },
	{ 1792, 0 },
	{ 1536, 255 },
	{ 1792, 255 },
	{ 1024, 0 },
	{ 1280, 0 },
	{ 1024, 255 },
	{ 1280, 255 },
	{ 2048, 0 },
	{ 2304, 0 },
	{ 2048, 255 },
	{ 2304, 255 },
	{ 3072, 0 },
	{ 3328, 0 },
	{ 3072, 255 },
	{ 3328, 255 },
	{ 2560, 0 },
	{ 2816, 0 },
	{ 2560, 255 },
	{ 2816, 255 }
};

SA2B_VertexData vertex_0001041C[] = {	{ 1, 12, 24, 65, position_000101DC, 288 },
	{ 3, 4, 24, 166, vcolor_000102FC, 96 },
	{ 5, 4, 48, 56, uv_0001035C, 192 },
	{ 255, 0, 0, 0, NULL, 0 }
 };

SA2B_ParameterData parameter_0001045C[] = {
	{ 0, 0, 0, 0, 0x11400 },
	{ 0, 0, 0, 0, 0x36A00 },
	{ 1, 0, 0, 0, 0x888 },
	{ 0, 0, 0, 0, 0x58308 },
	{ 4, 0, 0, 0, 0x6500 },
	{ 2, 0, 0, 0, 0x10B11 },
	{ 5, 0, 0, 0, 0xFFFFFFFF },
	{ 8, 0, 0, 0, 0x4001E },
	{ 9, 0, 0, 0, 4 },
	{ 10, 0, 0, 0, 0x104A }
};

SA2B_ParameterData parameter_000104AC[] = {
	{ 8, 0, 0, 0, 0x4001F }
};

Uint8 primitive_000104C0[] = {
0x90, 0x0, 0x24, 0x10, 0x10, 0x2, 0x5, 0x5, 0x1, 0x4, 0x4, 0x0, 0x5, 0x5, 0x1, 0x10, 0x10, 0x2, 0xF, 0xF, 0x3, 0xE, 0xE, 0x6, 0x7, 0x7, 0x5, 0x6, 0x6, 0x4, 0x7, 0x7, 0x5, 0xE, 0xE, 0x6, 0xD, 0xD, 0x7, 0x11, 0x11, 0xA, 0x9, 0x9, 0x9, 0x8, 0x8, 0x8, 0x9, 0x9, 0x9, 0x11, 0x11, 0xA, 0x13, 0x13, 0xB, 0x14, 0x14, 0xE, 0x3, 0x3, 0xD, 0x2, 0x2, 0xC, 0x3, 0x3, 0xD, 0x14, 0x14, 0xE, 0x12, 0x12, 0xF, 0x15, 0x15, 0x12, 0xB, 0xB, 0x11, 0xA, 0xA, 0x10, 0xB, 0xB, 0x11, 0x15, 0x15, 0x12, 0x17, 0x17, 0x13, 0x0, 0x0, 0x16, 0x1, 0x1, 0x15, 0xC, 0xC, 0x14, 0x1, 0x1, 0x15, 0x0, 0x0, 0x16, 0x16, 0x16, 0x17, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0};

Uint8 primitive_00010540[] = {
0x90, 0x0, 0x24, 0x12, 0x12, 0x1A, 0x4, 0x4, 0x19, 0x3, 0x3, 0x18, 0x4, 0x4, 0x19, 0x12, 0x12, 0x1A, 0x10, 0x10, 0x1B, 0xD, 0xD, 0x1E, 0x8, 0x8, 0x1D, 0x7, 0x7, 0x1C, 0x8, 0x8, 0x1D, 0xD, 0xD, 0x1E, 0x11, 0x11, 0x1F, 0xF, 0xF, 0x22, 0x6, 0x6, 0x21, 0x5, 0x5, 0x20, 0x6, 0x6, 0x21, 0xF, 0xF, 0x22, 0xE, 0xE, 0x23, 0x13, 0x13, 0x26, 0xA, 0xA, 0x25, 0x9, 0x9, 0x24, 0xA, 0xA, 0x25, 0x13, 0x13, 0x26, 0x15, 0x15, 0x27, 0x16, 0x16, 0x2A, 0x2, 0x2, 0x29, 0x1, 0x1, 0x28, 0x2, 0x2, 0x29, 0x16, 0x16, 0x2A, 0x14, 0x14, 0x2B, 0x17, 0x17, 0x2E, 0xC, 0xC, 0x2D, 0xB, 0xB, 0x2C, 0xC, 0xC, 0x2D, 0x17, 0x17, 0x2E, 0x0, 0x0, 0x2F, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0};

SA2B_GeometryData tpoly_000105C0[] = {	{ parameter_0001045C, 10, primitive_000104C0, 128 },
	{ parameter_000104AC, 1, primitive_00010540, 128 }
 };

SA2B_Model attach_000105E0 = { vertex_0001041C, 0, NULL, tpoly_000105C0, 0, LengthOfArray<Uint16>(tpoly_000105C0), { 0, -93.5f, 0 }, 1195.9441f };

NJS_OBJECT object_ghero_nk_kumoback_kumoback = { NJD_EVAL_UNIT_POS | NJD_EVAL_UNIT_ANG | NJD_EVAL_UNIT_SCL | NJD_EVAL_BREAK, &attach_000105E0, 0, 0, 0, 0, 0, 0, 1, 1, 1, NULL, NULL };
