#pragma once
enum 
{
	PVP_NCZ = 0x0,
	PVP_NCN = 0x1,
	PVP_HCZ = 0x2,
	PVP_HCN = 0x3,
	PVP_HCS = 0x4,
	PVP_HCF = 0x5,
	PVP_HCR = 0x6,
	PVP_HCP = 0x7,
	PVP_DCZ = 0x8,
	PVP_HNZ = 0x9,
	PVP_HNN = 0xA,
	PVP_HNS = 0xB,
	PVP_HNF = 0xC,
	PVP_HNR = 0xD,
	PVP_HNP = 0xE,
	PVP_HSZ = 0xF,
	PVP_HSN = 0x10,
	PVP_HSS = 0x11,
	PVP_HSF = 0x12,
	PVP_HSR = 0x13,
	PVP_HSP = 0x14,
	PVP_HFZ = 0x15,
	PVP_HFN = 0x16,
	PVP_HFS = 0x17,
	PVP_HFF = 0x18,
	PVP_HFR = 0x19,
	PVP_HFP = 0x1A,
	PVP_HRZ = 0x1B,
	PVP_HRN = 0x1C,
	PVP_HRS = 0x1D,
	PVP_HRF = 0x1E,
	PVP_HRR = 0x1F,
	PVP_HRP = 0x20,
	PVP_HPZ = 0x21,
	PVP_HPN = 0x22,
	PVP_HPS = 0x23,
	PVP_HPF = 0x24,
	PVP_HPR = 0x25,
	PVP_HPP = 0x26,
#ifdef NEUTPALETTE
	PVP_NNZ,
	PVP_NNN,
	PVP_NNS,
	PVP_NNF,
	PVP_NNR,
	PVP_NNP,
#endif
#ifdef DARKPALETTE
	PVP_DFZ,
	PVP_DFN,
	PVP_DFS,
	PVP_DFF,
	PVP_DFR,
	PVP_DFP,

	PVP_DNZ,
	PVP_DNN,
	PVP_DNS,
	PVP_DNF,
	PVP_DNR,
	PVP_DNP,
#endif
	PVP_COUNT
};
void alpalSetBank(ObjectMaster* a1, int a2);
void AL_Palette_Init();