#include "stdafx.h"
#include "AL_ModAPI.h"

NJS_TEXNAME AL_DX_PARTS_TEX_TEXNAME[129];
NJS_TEXLIST AL_DX_PARTS_TEX_TEXLIST = { arrayptrandlength(AL_DX_PARTS_TEX_TEXNAME) };

NJS_TEXNAME AL_SANDHOLE_TEXNAME[2];
NJS_TEXLIST AL_SANDHOLE_TEXLIST = { arrayptrandlength(AL_SANDHOLE_TEXNAME) };

NJS_TEXNAME BIRTHDAYHAT_TEXNAME[10];
NJS_TEXLIST BIRTHDAYHAT_TEXLIST = { arrayptrandlength(BIRTHDAYHAT_TEXNAME) };

NJS_TEXNAME timeofdayTexnames[100]; //reserved 100 to be sure
NJS_TEXLIST timeofdayTexlistReplacer = { timeofdayTexnames, 100 };

NJS_TEXNAME AL_ITEM_TEXNAME[ChaoItemCategory_Count];
NJS_TEXLIST AL_ITEM_TEXLIST = { AL_ITEM_TEXNAME, ChaoItemCategory_Count };

NJS_TEXNAME osamenu_tex[9];
NJS_TEXLIST AL_OSAMENU = { osamenu_tex, 9 };

NJS_TEXNAME CWE_OBJECT_TEXNAME[67];
NJS_TEXLIST CWE_OBJECT_TEXLIST = { CWE_OBJECT_TEXNAME, 67 };

NJS_TEXNAME AL_DRAWING_TEXNAME[21];
NJS_TEXLIST AL_DRAWING_TEXLIST = { AL_DRAWING_TEXNAME, 21 };

NJS_TEXNAME CWE_UI_TEXNAME[36];
NJS_TEXLIST CWE_UI_TEXLIST = { CWE_UI_TEXNAME, 36 };

NJS_TEXNAME OMO_EYE_TEXNAME[11];
NJS_TEXLIST OMO_EYE_TEXLIST = { OMO_EYE_TEXNAME, 11 };

NJS_TEXNAME NAME_ODE_TEXNAME[2];
NJS_TEXLIST NAME_ODE_TEXLIST = { NAME_ODE_TEXNAME, 2 };

NJS_TEXNAME AL_ODE_GUEST_TEXNAME[3];
NJS_TEXLIST AL_ODE_GUEST_TEXLIST = { AL_ODE_GUEST_TEXNAME, 3 };

NJS_TEXNAME XL_BODY_TEXNAME[143];
NJS_TEXLIST XL_BODY_TEXLIST = { XL_BODY_TEXNAME, 143 };

#define LENSTEX(name) NJS_TEXNAME name## _TEXNAME[7]; \
					  NJS_TEXLIST name## _TEXLIST = { name## _TEXNAME, 7 };

#define NEWLENSTEX(name) NJS_TEXNAME name## _TEXNAME[8]; \
					  NJS_TEXLIST name## _TEXLIST = { name## _TEXNAME, 8 };

LENSTEX(CWE_LENS_GREEN)
LENSTEX(CWE_LENS_MAGENTA)
LENSTEX(CWE_LENS_PURPLE)
LENSTEX(CWE_LENS_RED)
LENSTEX(CWE_LENS_YELLOW)
LENSTEX(CWE_LENS_SPARTOI)
LENSTEX(CWE_LENS_SNAKE)
LENSTEX(CWE_LENS_ROBOT)
NEWLENSTEX(CWE_LENS_AQUA)
NEWLENSTEX(CWE_LENS_JEWEL_BLUE)
NEWLENSTEX(CWE_LENS_JEWEL_YELLOW)
NEWLENSTEX(CWE_LENS_JEWEL_GREEN)
NEWLENSTEX(CWE_LENS_JEWEL_PURPLE)
NEWLENSTEX(CWE_LENS_JEWEL_RED)
NEWLENSTEX(CWE_LENS_JEWEL_SILVER)

void CWE_RegisterTexlists(const CWE_REGAPI* cwe_api) {
	cwe_api->RegisterChaoTexlistLoad("al_minda", &AL_SANDHOLE_TEXLIST);
	cwe_api->RegisterChaoTexlistLoad("birthdayhat", &BIRTHDAYHAT_TEXLIST);
	cwe_api->RegisterChaoTexlistLoad("CWE_OBJECT", &CWE_OBJECT_TEXLIST);
	cwe_api->RegisterChaoTexlistLoad("AL_OSAMENU_TEX_E", &AL_OSAMENU);
	cwe_api->RegisterChaoTexlistLoad("AL_ITEM", &AL_ITEM_TEXLIST);
	cwe_api->RegisterChaoTexlistLoad("NAME_ODE", &NAME_ODE_TEXLIST);
	cwe_api->RegisterChaoTexlistLoad("al_ode_guest", &AL_ODE_GUEST_TEXLIST);
	cwe_api->RegisterChaoTexlistLoad("CWE_UI", &CWE_UI_TEXLIST);
	cwe_api->RegisterChaoTexlistLoad("AL_DRAWING", &AL_DRAWING_TEXLIST);
	cwe_api->RegisterChaoTexlistLoad("OMO_EYE", &OMO_EYE_TEXLIST);
	cwe_api->RegisterChaoTexlistLoad("XL_BODY", &XL_BODY_TEXLIST);
	cwe_api->RegisterChaoTexlistLoad("AL_DX_PARTS_TEX", &AL_DX_PARTS_TEX_TEXLIST);
}