#pragma once
#include "SA2ModLoader.h"
#include "AL_ModAPI.h"

DataPointer(NJS_TEXLIST, AL_BODY, 0x013669FC);
DataPointer(NJS_TEXLIST, AL_EYE_TEXLIST, 0x01366AC4);
DataPointer(NJS_TEXLIST, AL_MOUTH_TEXLIST, 0x01366ADC);
DataPointer(NJS_TEXLIST, AL_OBJECT_TEXLIST, 0x01366AF4);
DataPointer(NJS_TEXLIST, al_mini_parts_tex_texlist, 0x01366AE4);
DataPointer(NJS_TEXLIST, al_minimal_texlist, 0x01366AEC);
DataPointer(NJS_TEXLIST, stru_1366AD4, 0x01366AD4);
DataPointer(NJS_TEXLIST, AL_TOY_TEXLIST, 0x01366AFC);

#define EXTERNLENS(name) extern NJS_TEXLIST name## _TEXLIST ;
EXTERNLENS(CWE_LENS_GREEN)
EXTERNLENS(CWE_LENS_MAGENTA)
EXTERNLENS(CWE_LENS_PURPLE)
EXTERNLENS(CWE_LENS_RED)
EXTERNLENS(CWE_LENS_YELLOW)
EXTERNLENS(CWE_LENS_SPARTOI)
EXTERNLENS(CWE_LENS_SNAKE)
EXTERNLENS(CWE_LENS_ROBOT)
EXTERNLENS(CWE_LENS_AQUA)
EXTERNLENS(CWE_LENS_JEWEL_BLUE)
EXTERNLENS(CWE_LENS_JEWEL_YELLOW)
EXTERNLENS(CWE_LENS_JEWEL_GREEN)
EXTERNLENS(CWE_LENS_JEWEL_PURPLE)
EXTERNLENS(CWE_LENS_JEWEL_RED)
EXTERNLENS(CWE_LENS_JEWEL_SILVER)

extern NJS_TEXLIST AL_ODE_GUEST_TEXLIST;
extern NJS_TEXLIST AL_SANDHOLE_TEXLIST;
extern NJS_TEXLIST CWE_OBJECT_TEXLIST;
extern NJS_TEXLIST timeofdayTexlistReplacer;
extern NJS_TEXNAME XL_BODY_TEXNAME[143];
extern NJS_TEXLIST XL_BODY_TEXLIST;
extern NJS_TEXLIST NAME_ODE_TEXLIST;
extern NJS_TEXLIST BIRTHDAYHAT_TEXLIST;
extern NJS_TEXLIST CWE_UI_TEXLIST;
extern NJS_TEXLIST AL_DRAWING_TEXLIST;
extern NJS_TEXLIST OMO_EYE_TEXLIST;
extern NJS_TEXLIST AL_OSAMENU;
extern NJS_TEXLIST AL_ITEM_TEXLIST;
extern NJS_TEXLIST AL_DX_PARTS_TEX_TEXLIST;

void CWE_RegisterTexlists(const CWE_REGAPI_LEGACY* cwe_api);