#pragma once

// all the old fusion enums renamed are stored here for now

enum ChaoGrade : __int8
{
	ChaoGrade_E = 0x0,
	ChaoGrade_D = 0x1,
	ChaoGrade_C = 0x2,
	ChaoGrade_B = 0x3,
	ChaoGrade_A = 0x4,
	ChaoGrade_S = 0x5,
};

enum ChaoEyes : __int8
{
	ChaoEyes_Normal = 0x0,
	ChaoEyes_Painful = 0x1,
	ChaoEyes_ClosedStraight = 0x2,
	ChaoEyes_ClosedHappy = 0x3,
	ChaoEyes_ClosedUp = 0x4,
	ChaoEyes_Tiny = 0x5,
	ChaoEyes_Circles = 0x6,
	ChaoEyes_ClosedDown = 0x7,
	ChaoEyes_Tiny2 = 0x8,
	ChaoEyes_HalfClosed = 0x9,
	ChaoEyes_Mean = 0xA,
	ChaoEyes_GreenChaos = 0xB,
	ChaoEyes_BlueChaos = 0xC,
	ChaoEyes_YellowChaos = 0xD,
};

enum ChaoMedal : __int8
{
	ChaoMedal_None = 0x0,
	ChaoMedal_Aquamarine = 0x1,
	ChaoMedal_Topaz = 0x2,
	ChaoMedal_Peridot = 0x3,
	ChaoMedal_Garnet = 0x4,
	ChaoMedal_Onyx = 0x5,
	ChaoMedal_Diamond = 0x6,
	ChaoMedal_Beginner = 0x7,
	ChaoMedal_Challenge = 0x8,
	ChaoMedal_Hero = 0x9,
	ChaoMedal_Dark = 0xA,
	ChaoMedal_Pearl = 0xB,
	ChaoMedal_Amethyst = 0xC,
	ChaoMedal_Emerald = 0xD,
	ChaoMedal_Ruby = 0xE,
	ChaoMedal_Sapphire = 0xF,
};

enum ChaoMouth : __int8
{
	ChaoMouth_None = 0x0,
	ChaoMouth_ToothySmile = 0x1,
	ChaoMouth_Open = 0x2,
	ChaoMouth_ClosedSmile = 0x3,
	ChaoMouth_ClosedFrown = 0x4,
	ChaoMouth_OpenSmile = 0x5,
	ChaoMouth_OpenFrown = 0x6,
	ChaoMouth_ClosedSmile2 = 0x7,
	ChaoMouth_Squiggly = 0x8,
	ChaoMouth_ToothyFrown = 0x9,
	ChaoMouth_ClosedFrown2 = 0xA,
	ChaoMouth_WideOpen = 0xB,
	ChaoMouth_ClosedFrown3 = 0xC,
	ChaoMouth_StraightMoustache = 0xD,
	ChaoMouth_SquigglyMoustache1 = 0xE,
	ChaoMouth_SquigglyMoustache2 = 0xF,
};

enum ChaoColor : __int8
{
	ChaoColor_Normal = 0x0,
	ChaoColor_Yellow = 0x1,
	ChaoColor_White = 0x2,
	ChaoColor_Brown = 0x3,
	ChaoColor_SkyBlue = 0x4,
	ChaoColor_Pink = 0x5,
	ChaoColor_Blue = 0x6,
	ChaoColor_Grey = 0x7,
	ChaoColor_Green = 0x8,
	ChaoColor_Red = 0x9,
	ChaoColor_LimeGreen = 0xA,
	ChaoColor_Purple = 0xB,
	ChaoColor_Orange = 0xC,
	ChaoColor_Black = 0xD,
};

enum ChaoEggColor : __int8
{
	ChaoEggColor_Normal = 0x0,
	ChaoEggColor_Yellow_MonoTone = 0x1,
	ChaoEggColor_White_MonoTone = 0x2,
	ChaoEggColor_Brown_MonoTone = 0x3,
	ChaoEggColor_SkyBlue_MonoTone = 0x4,
	ChaoEggColor_Pink_MonoTone = 0x5,
	ChaoEggColor_Blue_MonoTone = 0x6,
	ChaoEggColor_Grey_MonoTone = 0x7,
	ChaoEggColor_Green_MonoTone = 0x8,
	ChaoEggColor_Red_MonoTone = 0x9,
	ChaoEggColor_LimeGreen_MonoTone = 0xA,
	ChaoEggColor_Purple_MonoTone = 0xB,
	ChaoEggColor_Orange_MonoTone = 0xC,
	ChaoEggColor_Black_MonoTone = 0xD,
	ChaoEggColor_Yellow_TwoTone = 0xE,
	ChaoEggColor_White_TwoTone = 0xF,
	ChaoEggColor_Brown_TwoTone = 0x10,
	ChaoEggColor_SkyBlue_TwoTone = 0x11,
	ChaoEggColor_Pink_TwoTone = 0x12,
	ChaoEggColor_Blue_TwoTone = 0x13,
	ChaoEggColor_Grey_TwoTone = 0x14,
	ChaoEggColor_Green_TwoTone = 0x15,
	ChaoEggColor_Red_TwoTone = 0x16,
	ChaoEggColor_LimeGreen_TwoTone = 0x17,
	ChaoEggColor_Purple_TwoTone = 0x18,
	ChaoEggColor_Orange_TwoTone = 0x19,
	ChaoEggColor_Black_TwoTone = 0x1A,
	ChaoEggColor_NormalShiny = 0x1B,
	ChaoEggColor_YellowShiny_MonoTone = 0x1C,
	ChaoEggColor_WhiteShiny_MonoTone = 0x1D,
	ChaoEggColor_BrownShiny_MonoTone = 0x1E,
	ChaoEggColor_SkyBlueShiny_MonoTone = 0x1F,
	ChaoEggColor_PinkShiny_MonoTone = 0x20,
	ChaoEggColor_BlueShiny_MonoTone = 0x21,
	ChaoEggColor_GreyShiny_MonoTone = 0x22,
	ChaoEggColor_GreenShiny_MonoTone = 0x23,
	ChaoEggColor_RedShiny_MonoTone = 0x24,
	ChaoEggColor_LimeGreenShiny_MonoTone = 0x25,
	ChaoEggColor_PurpleShiny_MonoTone = 0x26,
	ChaoEggColor_OrangeShiny_MonoTone = 0x27,
	ChaoEggColor_BlackShiny_MonoTone = 0x28,
	ChaoEggColor_YellowShiny_TwoTone = 0x29,
	ChaoEggColor_WhiteShiny_TwoTone = 0x2A,
	ChaoEggColor_BrownShiny_TwoTone = 0x2B,
	ChaoEggColor_SkyBlueShiny_TwoTone = 0x2C,
	ChaoEggColor_PinkShiny_TwoTone = 0x2D,
	ChaoEggColor_BlueShiny_TwoTone = 0x2E,
	ChaoEggColor_GreyShiny_TwoTone = 0x2F,
	ChaoEggColor_GreenShiny_TwoTone = 0x30,
	ChaoEggColor_RedShiny_TwoTone = 0x31,
	ChaoEggColor_LimeGreenShiny_TwoTone = 0x32,
	ChaoEggColor_PurpleShiny_TwoTone = 0x33,
	ChaoEggColor_OrangeShiny_TwoTone = 0x34,
	ChaoEggColor_BlackShiny_TwoTone = 0x35,
	ChaoEggColor_GlitchyNormal = 0x36,
};


enum ChaoTexture : __int8
{
	ChaoTexture_None = 0x0,
	ChaoTexture_YellowJewel = 0x1,
	ChaoTexture_WhiteJewel = 0x2,
	ChaoTexture_PinkJewel = 0x3,
	ChaoTexture_BlueJewel = 0x4,
	ChaoTexture_GreenJewel = 0x5,
	ChaoTexture_PurpleJewel = 0x6,
	ChaoTexture_SkyBlueJewel = 0x7,
	ChaoTexture_RedJewel = 0x8,
	ChaoTexture_BlackJewel = 0x9,
	ChaoTexture_LimeGreenJewel = 0xA,
	ChaoTexture_OrangeJewel = 0xB,
	ChaoTexture_Pearl = 0xC,
	ChaoTexture_Metal1 = 0xD,
	ChaoTexture_Metal2 = 0xE,
	ChaoTexture_Glass = 0xF,
	ChaoTexture_Moon = 0x10,
};

enum SA2BAnimal : __int8
{
	SA2BAnimal_None = -1,
	SA2BAnimal_Penguin = 0x0,
	SA2BAnimal_Seal = 0x1,
	SA2BAnimal_Otter = 0x2,
	SA2BAnimal_Rabbit = 0x3,
	SA2BAnimal_Cheetah = 0x4,
	SA2BAnimal_Warthog = 0x5,
	SA2BAnimal_Bear = 0x6,
	SA2BAnimal_Tiger = 0x7,
	SA2BAnimal_Gorilla = 0x8,
	SA2BAnimal_Peacock = 0x9,
	SA2BAnimal_Parrot = 0xA,
	SA2BAnimal_Condor = 0xB,
	SA2BAnimal_Skunk = 0xC,
	SA2BAnimal_Sheep = 0xD,
	SA2BAnimal_Raccoon = 0xE,
	SA2BAnimal_HalfFish = 0xF,
	SA2BAnimal_SkeletonDog = 0x10,
	SA2BAnimal_Bat = 0x11,
	SA2BAnimal_Dragon = 0x12,
	SA2BAnimal_Unicorn = 0x13,
	SA2BAnimal_Phoenix = 0x14,
	SA2BAnimal_YellowChaosDrive = 0x15,
	SA2BAnimal_GreenChaosDrive = 0x16,
	SA2BAnimal_RedChaosDrive = 0x17,
	SA2BAnimal_PurpleChaosDrive = 0x18,
};

enum SADXAnimal : __int8
{
	SADXAnimal_None = -1,
	SADXAnimal_Seal = 0x0,
	SADXAnimal_Penguin = 0x1,
	SADXAnimal_Otter = 0x2,
	SADXAnimal_Peacock = 0x3,
	SADXAnimal_Swallow = 0x4,
	SADXAnimal_Parrot = 0x5,
	SADXAnimal_Deer = 0x6,
	SADXAnimal_Rabbit = 0x7,
	SADXAnimal_Kangaroo = 0x8,
	SADXAnimal_Gorilla = 0x9,
	SADXAnimal_Lion = 0xA,
	SADXAnimal_Elephant = 0xB,
	SADXAnimal_Mole = 0xC,
	SADXAnimal_Koala = 0xD,
	SADXAnimal_Skunk = 0xE,
};

enum ChaoFruit : __int8
{
	ChaoFruit_None = -1,
	ChaoFruit_ChaoGardenFruit = 0x0,
	ChaoFruit_HeroGardenFruit = 0x1,
	ChaoFruit_DarkGardenFruit = 0x2,
	ChaoFruit_StrongFruit = 0x3,
	ChaoFruit_TastyFruit = 0x4,
	ChaoFruit_HeroFruit = 0x5,
	ChaoFruit_DarkFruit = 0x6,
	ChaoFruit_RoundFruit = 0x7,
	ChaoFruit_TriangleFruit = 0x8,
	ChaoFruit_SquareFruit = 0x9,
	ChaoFruit_HeartFruit = 0xA,
	ChaoFruit_ChaoFruit = 0xB,
	ChaoFruit_Mushroom = 0x14,
	ChaoFruit_MushroomAlt = 0x15,
	ChaoFruit_OrangeFruit = 0xD,
	ChaoFruit_BlueFruit = 0xE,
	ChaoFruit_PinkFruit = 0xF,
	ChaoFruit_GreenFruit = 0x10,
	ChaoFruit_PurpleFruit = 0x11,
	ChaoFruit_YellowFruit = 0x12,
	ChaoFruit_RedFruit = 0x13,
	ChaoFruit_SmartFruit = 0xC,
	ChaoFruit_MintCandy = 0x16,
	ChaoFruit_Grapes = 0x17,
};

enum ChaoHat : __int8
{
	ChaoHat_None = 0x0,
	ChaoHat_Pumpkin = 0x1,
	ChaoHat_Skull = 0x2,
	ChaoHat_Apple = 0x3,
	ChaoHat_Bucket = 0x4,
	ChaoHat_EmptyCan = 0x5,
	ChaoHat_CardboardBox = 0x6,
	ChaoHat_FlowerPot = 0x7,
	ChaoHat_PaperBag = 0x8,
	ChaoHat_Pan = 0x9,
	ChaoHat_Stump = 0xA,
	ChaoHat_Watermelon = 0xB,
	ChaoHat_RedWoolBeanie = 0xC,
	ChaoHat_BlueWoolBeanie = 0xD,
	ChaoHat_BlackWoolBeanie = 0xE,
	ChaoHat_Pacifier = 0xF,
	ChaoHat_NormalEggShell = 0x10,
	ChaoHat_Yellow_MonoTone_EggShell = 0x11,
	ChaoHat_White_MonoTone_EggShell = 0x12,
	ChaoHat_Brown_MonoTone_EggShell = 0x13,
	ChaoHat_SkyBlue_MonoTone_EggShell = 0x14,
	ChaoHat_Pink_MonoTone_EggShell = 0x15,
	ChaoHat_Blue_MonoTone_EggShell = 0x16,
	ChaoHat_Grey_MonoTone_EggShell = 0x17,
	ChaoHat_Green_MonoTone_EggShell = 0x18,
	ChaoHat_Red_MonoTone_EggShell = 0x19,
	ChaoHat_LimeGreen_MonoTone_EggShell = 0x1A,
	ChaoHat_Purple_MonoTone_EggShell = 0x1B,
	ChaoHat_Orange_MonoTone_EggShell = 0x1C,
	ChaoHat_Black_MonoTone_EggShell = 0x1D,
	ChaoHat_Yellow_TwoTone_EggShell = 0x1E,
	ChaoHat_White_TwoTone_EggShell = 0x1F,
	ChaoHat_Brown_TwoTone_EggShell = 0x20,
	ChaoHat_SkyBlue_TwoTone_EggShell = 0x21,
	ChaoHat_Pink_TwoTone_EggShell = 0x22,
	ChaoHat_Blue_TwoTone_EggShell = 0x23,
	ChaoHat_Grey_TwoTone_EggShell = 0x24,
	ChaoHat_Green_TwoTone_EggShell = 0x25,
	ChaoHat_Red_TwoTone_EggShell = 0x26,
	ChaoHat_LimeGreen_TwoTone_EggShell = 0x27,
	ChaoHat_Purple_TwoTone_EggShell = 0x28,
	ChaoHat_Orange_TwoTone_EggShell = 0x29,
	ChaoHat_Black_TwoTone_EggShell = 0x2A,
	ChaoHat_NormalShinyEggShell = 0x2B,
	ChaoHat_YellowShiny_MonoTone_EggShell = 0x2C,
	ChaoHat_WhiteShiny_MonoTone_EggShell = 0x2D,
	ChaoHat_BrownShiny_MonoTone_EggShell = 0x2E,
	ChaoHat_SkyBlueShiny_MonoTone_EggShell = 0x2F,
	ChaoHat_PinkShiny_MonoTone_EggShell = 0x30,
	ChaoHat_BlueShiny_MonoTone_EggShell = 0x31,
	ChaoHat_GreyShiny_MonoTone_EggShell = 0x32,
	ChaoHat_GreenShiny_MonoTone_EggShell = 0x33,
	ChaoHat_RedShiny_MonoTone_EggShell = 0x34,
	ChaoHat_LimeGreenShiny_MonoTone_EggShell = 0x35,
	ChaoHat_PurpleShiny_MonoTone_EggShell = 0x36,
	ChaoHat_OrangeShiny_MonoTone_EggShell = 0x37,
	ChaoHat_BlackShiny_MonoTone_EggShell = 0x38,
	ChaoHat_YellowShiny_TwoTone_EggShell = 0x39,
	ChaoHat_WhiteShiny_TwoTone_EggShell = 0x3A,
	ChaoHat_BrownShiny_TwoTone_EggShell = 0x3B,
	ChaoHat_SkyBlueShiny_TwoTone_EggShell = 0x3C,
	ChaoHat_PinkShiny_TwoTone_EggShell = 0x3D,
	ChaoHat_BlueShiny_TwoTone_EggShell = 0x3E,
	ChaoHat_GreyShiny_TwoTone_EggShell = 0x3F,
	ChaoHat_GreenShiny_TwoTone_EggShell = 0x40,
	ChaoHat_RedShiny_TwoTone_EggShell = 0x41,
	ChaoHat_LimeGreenShiny_TwoTone_EggShell = 0x42,
	ChaoHat_PurpleShiny_TwoTone_EggShell = 0x43,
	ChaoHat_OrangeShiny_TwoTone_EggShell = 0x44,
	ChaoHat_BlackShiny_TwoTone_EggShell = 0x45,
	ChaoHat_YellowJewelEggShell = 0x46,
	ChaoHat_WhiteJewelEggShell = 0x47,
	ChaoHat_PinkJewelEggShell = 0x48,
	ChaoHat_BlueJewelEggShell = 0x49,
	ChaoHat_GreenJewelEggShell = 0x4A,
	ChaoHat_PurpleJewelEggShell = 0x4B,
	ChaoHat_AquaJewelEggShell = 0x4C,
	ChaoHat_RedJewelEggShell = 0x4D,
	ChaoHat_BlackJewelEggShell = 0x4E,
	ChaoHat_LightGreenJewelEggShell = 0x4F,
	ChaoHat_OrangeJewelEggShell = 0x50,
	ChaoHat_PearlEggShell = 0x51,
	ChaoHat_Metal1EggShell = 0x52,
	ChaoHat_Metal2EggShell = 0x53,
	ChaoHat_GlassEggShell = 0x54,
};

enum ChaoSeed : __int8
{
	ChaoSeed_None = -1,
	ChaoSeed_StrongSeed = 0x0,
	ChaoSeed_TastySeed = 0x1,
	ChaoSeed_HeroSeed = 0x2,
	ChaoSeed_DarkTheme = 0x3,
	ChaoSeed_RoundSeed = 0x4,
	ChaoSeed_TriangleTheme = 0x5,
	ChaoSeed_SquareSeed = 0x6,
};