add_library(CWE SHARED
    BrightFix/BrightFix.cpp
    al_animation.cpp
    alg_kinder_bl.cpp
    alg_kinder_cl.cpp
    alg_kinder_he.cpp
    alg_kinder_ortho.cpp
    alo_accessory.cpp
    alo_boat.cpp
    alo_coffin.cpp
    alo_fruit.cpp
    alo_obakehead.cpp
    alo_special.cpp
    playsound.cpp
    al_behavior/albhv_birthday.cpp
    al_behavior/albhv_bully.cpp
    al_behavior/albhv_boat.cpp
    al_behavior/albhv_capture.cpp
    al_behavior/albhv_coffin.cpp
    al_behavior/albhv_dance.cpp
    al_behavior/albhv_float.cpp
    al_behavior/albhv_glide.cpp
    al_behavior/albhv_life.cpp
    al_behavior/albhv_ltoy.cpp
    al_behavior/albhv_music.cpp
    al_behavior/albhv_piano.cpp
    al_behavior/albhv_posture.cpp
    al_behavior/albhv_rain.cpp
    al_behavior/albhv_stoy.cpp
    al_behavior/albhv_swim.cpp
    al_behavior/albhv_sunaasubi.cpp
    al_behavior/albhv_tree.cpp
    al_behavior/albhv_walk.cpp
    al_behavior/albhv_wrench.cpp
    al_behavior/alsbhv_chat.cpp
    al_behavior/alsbhv_common.cpp
    al_behavior/alsbhv_gossip.cpp
    al_behavior/alsbhv_holdhand.cpp
    al_behavior/alsbhv_hug.cpp
    al_behavior/alsbhv_mayu.cpp
    al_behavior/al_behavior.cpp
    al_garden_info.cpp
    al_hold.cpp
    al_landmark.cpp
    al_daynight_rain.cpp
    al_ode_mainmenubar.cpp
    api/api_accessory.cpp
    api/api_json.cpp
    api/api_metadata.cpp
    api/api_motion.cpp
    api/api_texture.cpp
    api/api_main.cpp
    chaofile.cpp
    cnk_util.cpp
    global_save.cpp
    hd_texture.cpp
    ModelInfo.cpp
    minimal/minimal.cpp
    move.cpp
    api/api_idhash.cpp
    renderfix.cpp
    save/save_item.cpp
    ui/al_tween_interp.cpp
    al_chao_counter.cpp
    al_edit.cpp
    al_emotion.cpp
    al_face.cpp
    al_behavior/al_intention.cpp
    al_behavior/al_knowledge.cpp
    al_butterfly.cpp
    al_customization.cpp
    al_daynight.cpp
    al_draw.cpp
    al_gene.cpp
    al_marketattr.cpp
    al_minimal.cpp
    al_misc.cpp
    AL_ModAPI.cpp
    al_modelcontainer.cpp
    al_motion.cpp
    al_msg_font.cpp
    al_msg_win.cpp
    al_name.cpp
    al_namedisplay.cpp
    al_odekake.cpp
    al_ode_guest.cpp
    al_ode_guide.cpp
    al_ode_hikkoshi.cpp
    al_ode_joycarry.cpp
    al_ode_nazukeya.cpp
    al_ode_storage.cpp
    al_omochao_build.cpp
    al_parameter.cpp
    al_field.cpp
    al_parts.cpp
    al_piano.cpp
    al_sandhole.cpp
    al_save.cpp
    al_shape.cpp
    al_social.cpp
    al_stage.cpp
    al_texlist.cpp
    al_toy_move.cpp
    al_world.cpp
    api/api_customchao.cpp
    api/api_msg.cpp
    api/api_tree.cpp
    Chao.cpp
    ChaoMain.cpp
    alo_float.cpp
    code_system/codes/code_animal_reuse.cpp
    code_system/codes/code_birthday.cpp
    code_system/codes/code_dccocoon.cpp
    code_system/codes/code_disjingle.cpp
    code_system/codes/code_drown.cpp
    code_system/codes/code_hdtoy.cpp
    code_system/codes/code_hunger.cpp
    code_system/codes/code_eggcolor.cpp
    code_system/codes/code_gardenlimit.cpp
    code_system/codes/code_monsterevo.cpp
    code_system/codes/code_personality.cpp
    code_system/codes/code_playerspeed.cpp
    code_system/codes/code_sick.cpp
    code_system/codes/code_karatemedal.cpp
    code_system/cwe_patch.cpp
    code_system/cwe_transpile.cpp
    collision_debug.cpp
    CWE.cpp
    al_palette.cpp
    code_system/cwe_codes.cpp
    al_growtree.cpp
    alg_kinder_co.cpp
    al_race.cpp
    cwe_fixes.cpp
    cwe_func.cpp
    c_colli.cpp
    IniFile.cpp
    kce_helper.cpp
    memory.cpp
    ninja_functions.cpp
    PaletteFix.cpp
    register/reg_accessory.cpp
    register/api_fruit.cpp
    register/api_minimal.cpp
    register/reg_motion.cpp
    register/api_register.cpp
    register/api_special.cpp
    save/save_serializable.cpp
    stdafx.cpp
    TextConv.cpp
    Trampoline.cpp
    ui/al_ortho.cpp
    land_grayscale.cpp
    cwe_c_colli.cpp
    navigation/external/Recast/Source/Recast.cpp
    navigation/external/Recast/Source/RecastAlloc.cpp
    navigation/external/Recast/Source/RecastArea.cpp
    navigation/external/Recast/Source/RecastAssert.cpp
    navigation/external/Recast/Source/RecastContour.cpp
    navigation/external/Recast/Source/RecastFilter.cpp
    navigation/external/Recast/Source/RecastLayers.cpp
    navigation/external/Recast/Source/RecastMesh.cpp
    navigation/external/Recast/Source/RecastMeshDetail.cpp
    navigation/external/Recast/Source/RecastRasterization.cpp
    navigation/external/Recast/Source/RecastRegion.cpp
    navigation/external/Detour/Source/DetourAlloc.cpp
    navigation/external/Detour/Source/DetourAssert.cpp
    navigation/external/Detour/Source/DetourCommon.cpp
    navigation/external/Detour/Source/DetourNavMesh.cpp
    navigation/external/Detour/Source/DetourNavMeshBuilder.cpp
    navigation/external/Detour/Source/DetourNavMeshQuery.cpp
    navigation/external/Detour/Source/DetourNode.cpp
    navigation/navsys_meshconvert.cpp
    navigation/navsys_generator.cpp
    navigation/navsys.cpp
    navigation/navsys_log.cpp
    al_behavior/albhv_navigation.cpp
)

if (IMGUIDEBUG)
    target_sources(CWE PRIVATE
        imgui_debug.cpp
        imgui/imgui.cpp
        imgui/imgui_demo.cpp      
        imgui/imgui_draw.cpp      
        imgui/imgui_impl_dx9.cpp
        imgui/imgui_impl_win32.cpp
        imgui/imgui_tables.cpp
        imgui/imgui_widgets.cpp
        navigation/navsys_debug.cpp
    )
endif()